-- ============================================================
-- BAT_ALARM_HIS
-- 배치 파일 미수신 알람 이력
-- ============================================================

CREATE TABLE BAT_ALARM_HIS (
    MBRSH_PGM_ID    VARCHAR2(1)     NOT NULL,
    FILE_ID         VARCHAR2(10)    NOT NULL,
    FILE_NM         VARCHAR2(500)   NOT NULL,
    ALARM_ID        NUMBER          NOT NULL,
    ALARM_DT        DATE,
    FREQUENCY_TYPE  VARCHAR2(20),
    EXP_MIN_TIME    VARCHAR2(8),
    EXP_MED_TIME    VARCHAR2(8),
    EXP_MAX_TIME    VARCHAR2(8),
    CHECK_TIME      VARCHAR2(8),
    DELAY_MIN       NUMBER(5),
    ANOMALY_SCORE   NUMBER(10,4),
    ALARM_MSG       VARCHAR2(2000),
    TGT_FILE_PATH   VARCHAR2(500),
    SEND_STS        VARCHAR2(1),
    SEND_DT         DATE,
    ERR_MSG         VARCHAR2(1000),
    REGR_ID         VARCHAR2(8),
    REG_DT          DATE,
    UPDR_ID         VARCHAR2(8),
    UPD_DT          DATE,
    CONSTRAINT PK_BAT_ALARM_HIS PRIMARY KEY (ALARM_ID)
);

COMMENT ON TABLE  BAT_ALARM_HIS                IS '배치 파일 미수신 알람 이력';
COMMENT ON COLUMN BAT_ALARM_HIS.MBRSH_PGM_ID   IS '멤버쉽프로그램ID';
COMMENT ON COLUMN BAT_ALARM_HIS.FILE_ID        IS '파일ID';
COMMENT ON COLUMN BAT_ALARM_HIS.FILE_NM        IS '파일명(COM_BATFILE_TRN 등 연계·동일 FILE_ID 구분용)';
COMMENT ON COLUMN BAT_ALARM_HIS.ALARM_ID       IS '알람ID(시퀀스)';
COMMENT ON COLUMN BAT_ALARM_HIS.ALARM_DT       IS '알람발생일시';
COMMENT ON COLUMN BAT_ALARM_HIS.FREQUENCY_TYPE IS '배치수신주기 (DAILY/WEEKLY/MONTHLY 등)';
COMMENT ON COLUMN BAT_ALARM_HIS.EXP_MIN_TIME   IS '예상도착시각 최솟값 (5th percentile)';
COMMENT ON COLUMN BAT_ALARM_HIS.EXP_MED_TIME   IS '예상도착시각 중앙값 (50th percentile)';
COMMENT ON COLUMN BAT_ALARM_HIS.EXP_MAX_TIME   IS '예상도착시각 최댓값 (95th percentile) · 알람기준';
COMMENT ON COLUMN BAT_ALARM_HIS.CHECK_TIME     IS '알람발생시각';
COMMENT ON COLUMN BAT_ALARM_HIS.DELAY_MIN      IS '마감시각 초과 분수';
COMMENT ON COLUMN BAT_ALARM_HIS.ANOMALY_SCORE  IS 'Isolation Forest 이상탐지 점수 (음수일수록 이상)';
COMMENT ON COLUMN BAT_ALARM_HIS.ALARM_MSG      IS 'EXAONE 생성 한국어 알람 메시지';
COMMENT ON COLUMN BAT_ALARM_HIS.TGT_FILE_PATH  IS '알람 txt 파일 경로';
COMMENT ON COLUMN BAT_ALARM_HIS.SEND_STS       IS '전송상태 0:대기 1:완료 9:실패';
COMMENT ON COLUMN BAT_ALARM_HIS.SEND_DT        IS '슬랙전송완료일시';
COMMENT ON COLUMN BAT_ALARM_HIS.ERR_MSG        IS '전송실패 에러메시지';
COMMENT ON COLUMN BAT_ALARM_HIS.REGR_ID        IS '등록자ID';
COMMENT ON COLUMN BAT_ALARM_HIS.REG_DT         IS '등록일시';
COMMENT ON COLUMN BAT_ALARM_HIS.UPDR_ID        IS '변경자ID';
COMMENT ON COLUMN BAT_ALARM_HIS.UPD_DT         IS '변경일시';

-- 인덱스: PK 외 추가 인덱스만 (동일 FILE_ID + 파일명 + 시계열 조회 대비)
--CREATE INDEX IDX_BAT_ALARM_DT   ON BAT_ALARM_HIS (ALARM_DT);
--CREATE INDEX IDX_BAT_ALARM_FILE ON BAT_ALARM_HIS (FILE_ID, FILE_NM, ALARM_DT);
--CREATE INDEX IDX_BAT_ALARM_STS  ON BAT_ALARM_HIS (SEND_STS, ALARM_DT);

COMMIT;
